import PrivateMessageItem from '../view/PrivateMessageItem';

const PrivateMessageList: PrivateMessageItem[] = [
  new PrivateMessageItem(1, '舞蹈达人', '你好，请问你对最新的舞蹈视频有什么建议吗？', 2, '10分钟前'),
  new PrivateMessageItem(2, '钢琴师凌枫', '我刚上传了新的钢琴曲，希望你能听听看。', 6, '20分钟前'),
  new PrivateMessageItem(3, '小提琴家星辰', '新曲《星空轨迹》已发布，期待你的反馈～', 1, '45分钟前'),
  new PrivateMessageItem(4, '吉他手雨萱', '尝试了电子与古典融合风格，听听看？', 3, '1小时前'),
  new PrivateMessageItem(5, '鼓手梦璃', '刚完成一首抒情单曲《雨后晴天》', 0, '昨天'),
  new PrivateMessageItem(6, '萨克斯风手清扬', '合作曲《光与影》已上线', 0, '半小时前'),
  new PrivateMessageItem(7, 'DJ晓晨', 'Remix版本《午夜漫游》发布', 0, '2小时前'),
  new PrivateMessageItem(8, '声乐导师子昂', '正在直播新曲创作过程', 5, '10分钟前'),
  new PrivateMessageItem(9, '古筝演奏家晚晴', '年度专辑先导单曲《起点》上线', 0, '3小时前'),
  new PrivateMessageItem(10, '作曲家冷轩', '来听听我的新歌《平行宇宙》', 0, '4小时前'),
  new PrivateMessageItem(11, '合唱团指挥莫离', '翻唱了经典曲目《岁月神偷》', 0, '昨天'),
];

export default PrivateMessageList;