import ThreeContentItem from '../model/ThreeContentItem'
import { CreatorList } from './CreatorList'

const work:ThreeContentItem[]=[
  new ThreeContentItem(0,CreatorList[0].name,$r('app.media.RecommendItemA'), '56万'),
  new ThreeContentItem(1,CreatorList[0].name,$r('app.media.RecommendItemB'), '99万'),
  new ThreeContentItem(2,CreatorList[0].name,$r('app.media.RecommendItemC'), '45万'),

  new ThreeContentItem(3,CreatorList[1].name,$r('app.media.RecommendItemB'), '90万'),
  new ThreeContentItem(4,CreatorList[1].name,$r('app.media.RecommendItemA'), '92万'),
  new ThreeContentItem(5,CreatorList[1].name,$r('app.media.RecommendItemC'), '45万'),

  new ThreeContentItem(6,CreatorList[2].name,$r("app.media.pixels"), '99万'),
  new ThreeContentItem(7,CreatorList[2].name,$r('app.media.RecommendItemA'), '99万'),
  new ThreeContentItem(8,CreatorList[2].name,$r('app.media.rock'), '45万'),

  new ThreeContentItem(9,CreatorList[3].name,$r('app.media.RecommendItemA'), '99万'),
  new ThreeContentItem(10,CreatorList[3].name,$r("app.media.pixels"), '40万'),
  new ThreeContentItem(11,CreatorList[3].name,$r('app.media.RecommendItemA'), '29万'),

  new ThreeContentItem(12,CreatorList[4].name,$r('app.media.rock'), '45万'),
  new ThreeContentItem(13,CreatorList[4].name,$r("app.media.pixels"), '99万'),
  new ThreeContentItem(14,CreatorList[4].name,$r('app.media.RecommendItemA'), '29万'),

  new ThreeContentItem(15,CreatorList[5].name,$r('app.media.RecommendItemA'), '45万'),
  new ThreeContentItem(16,CreatorList[5].name,$r("app.media.pixels"), '99万'),
  new ThreeContentItem(17,CreatorList[5].name,$r('app.media.RecommendItemA'), '59万'),

  new ThreeContentItem(18,CreatorList[6].name,$r('app.media.RecommendItemA'), '89万'),
  new ThreeContentItem(19,CreatorList[6].name,$r("app.media.pixels"), '45万'),
  new ThreeContentItem(20,CreatorList[6].name,$r('app.media.RecommendItemA'), '29万'),

  new ThreeContentItem(21,CreatorList[7].name,$r('app.media.RecommendItemB'), '99万'),
  new ThreeContentItem(22,CreatorList[7].name,$r("app.media.pixels"), '45万'),
  new ThreeContentItem(23,CreatorList[7].name,$r('app.media.RecommendItemA'), '99万'),

  new ThreeContentItem(24,CreatorList[1].name,$r('app.media.rock'), '99万'),
  new ThreeContentItem(25,CreatorList[2].name,$r("app.media.pixels"), '45万'),
  new ThreeContentItem(26,CreatorList[3].name,$r('app.media.RecommendItemA'), '99万'),

]

const likes:ThreeContentItem[]=[
  new ThreeContentItem(0,CreatorList[0].name,$r('app.media.RecommendItemA'), '56万'),
  new ThreeContentItem(1,CreatorList[0].name,$r('app.media.pixels'), '45万'),
  new ThreeContentItem(2,CreatorList[0].name,$r('app.media.RecommendItemA'), '99万'),

  new ThreeContentItem(3,CreatorList[1].name,$r('app.media.RecommendItemC'), '99万'),
  new ThreeContentItem(4,CreatorList[1].name,$r('app.media.RecommendItemA'), '45万'),
  new ThreeContentItem(5,CreatorList[1].name,$r('app.media.pixels'), '99万'),

  new ThreeContentItem(6,CreatorList[2].name,$r('app.media.RecommendItemC'), '79万'),
  new ThreeContentItem(7,CreatorList[2].name,$r('app.media.RecommendItemA'), '59万'),
  new ThreeContentItem(8,CreatorList[2].name,$r('app.media.RecommendItemB'), '39万'),

  new ThreeContentItem(9,CreatorList[3].name,$r('app.media.RecommendItemA'), '29万'),
  new ThreeContentItem(10,CreatorList[3].name,$r('app.media.RecommendItemB'), '39万'),
  new ThreeContentItem(11,CreatorList[3].name,$r('app.media.RecommendItemC'), '49万'),

  new ThreeContentItem(12,CreatorList[4].name,$r('app.media.RecommendItemA'), '969万'),
  new ThreeContentItem(13,CreatorList[4].name,$r('app.media.RecommendItemC'), '94万'),
  new ThreeContentItem(14,CreatorList[4].name,$r('app.media.pixels'), '99万'),

  new ThreeContentItem(15,CreatorList[5].name,$r('app.media.RecommendItemA'), '45万'),
  new ThreeContentItem(16,CreatorList[5].name,$r('app.media.RecommendItemC'), '99万'),
  new ThreeContentItem(17,CreatorList[5].name,$r('app.media.pixels'), '99万'),

  new ThreeContentItem(18,CreatorList[6].name,$r('app.media.RecommendItemA'), '56万'),
  new ThreeContentItem(19,CreatorList[6].name,$r('app.media.pixels'), '90万'),
  new ThreeContentItem(20,CreatorList[6].name,$r('app.media.RecommendItemB'), '99万'),

  new ThreeContentItem(21,CreatorList[7].name,$r('app.media.RecommendItemA'), '45万'),
  new ThreeContentItem(22,CreatorList[7].name,$r('app.media.pixels'), '99万'),
  new ThreeContentItem(23,CreatorList[7].name,$r('app.media.RecommendItemA'), '809万'),

  new ThreeContentItem(24,CreatorList[4].name,$r('app.media.QMusic'), '45万'),
  new ThreeContentItem(25,CreatorList[5].name,$r('app.media.pixels'), '99万'),
  new ThreeContentItem(26,CreatorList[6].name,$r('app.media.rock'), '809万'),
]


const collections:ThreeContentItem[]=[
  new ThreeContentItem(0,CreatorList[0].name,$r('app.media.pixels'), '99万'),
  new ThreeContentItem(1,CreatorList[0].name,$r('app.media.RecommendItemC'), '134万'),
  new ThreeContentItem(2,CreatorList[0].name,$r('app.media.RecommendItemA'), '18万'),

  new ThreeContentItem(3,CreatorList[1].name,$r('app.media.RecommendItemA'), '18万'),
  new ThreeContentItem(4,CreatorList[1].name,$r('app.media.RecommendItemC'), '156万'),
  new ThreeContentItem(5,CreatorList[1].name,$r('app.media.RecommendItemA'), '16万'),

  new ThreeContentItem(6,CreatorList[2].name,$r('app.media.RecommendItemA'), '126万'),
  new ThreeContentItem(7,CreatorList[2].name,$r('app.media.pixels'), '186万'),
  new ThreeContentItem(8,CreatorList[2].name,$r('app.media.RecommendItemA'), '182万'),

  new ThreeContentItem(9,CreatorList[3].name,$r('app.media.RecommendItemB'), '182万'),
  new ThreeContentItem(10,CreatorList[3].name,$r('app.media.RecommendItemA'), '132万'),
  new ThreeContentItem(11,CreatorList[3].name,$r('app.media.RecommendItemC'), '137万'),

  new ThreeContentItem(12,CreatorList[4].name,$r('app.media.RecommendItemA'), '54万'),
  new ThreeContentItem(13,CreatorList[4].name,$r('app.media.pixels'), '234万'),
  new ThreeContentItem(14,CreatorList[4].name,$r('app.media.RecommendItemA'), '134万'),

  new ThreeContentItem(15,CreatorList[5].name,$r('app.media.RecommendItemA'), '66万'),
  new ThreeContentItem(16,CreatorList[5].name,$r('app.media.RecommendItemB'), '256万'),
  new ThreeContentItem(17,CreatorList[5].name,$r('app.media.RecommendItemA'), '40万'),

  new ThreeContentItem(18,CreatorList[6].name,$r('app.media.RecommendItemA'), '30万'),
  new ThreeContentItem(19,CreatorList[6].name,$r('app.media.RecommendItemB'), '19万'),
  new ThreeContentItem(20,CreatorList[6].name,$r('app.media.RecommendItemA'), '188万'),

  new ThreeContentItem(21,CreatorList[7].name,$r('app.media.RecommendItemB'), '55万'),
  new ThreeContentItem(22,CreatorList[7].name,$r('app.media.pixels'), '99万'),
  new ThreeContentItem(23,CreatorList[7].name,$r('app.media.RecommendItemA'), '34万'),

  new ThreeContentItem(24,CreatorList[7].name,$r('app.media.RecommendItemB'), '55万'),
  new ThreeContentItem(25,CreatorList[0].name,$r('app.media.pixels'), '99万'),
  new ThreeContentItem(26,CreatorList[1].name,$r('app.media.QMusic'), '34万'),

]

export {work,likes,collections}
