import TrendingItem from '../model/TrendingItem'

const TrendingContentList: TrendingItem[] = [
  new TrendingItem(1, 'dance', '最新流行舞蹈教学，简单易学的舞步', '舞蹈视频','1.2万点赞', '254评论', '舞蹈达人', '0:45', $r("app.media.pixels"), $r('app.media.userA'),'Video/City_Night_View.mp4'),
  new TrendingItem(2, 'music', '《勋章》是由鹿晗演唱的励志歌曲','勋章', '2.5万点赞', '432评论', '音乐制作人', '3:35', $r("app.media.rock"), $r('app.media.userB'),'Music/勋章.mp3'),
  new TrendingItem(3, 'food', '10分钟快手菜，简单美味的家常料理','舞蹈视频','8.7万点赞', '1.2k评论', '美食博主', '3:24', $r("app.media.RecommendItemA"), $r('app.media.userC'),'Video/City_Night_View.mp4'),
  new TrendingItem(4, 'travel', '隐藏在城市里的秘境，周末小众游玩地推荐', '舞蹈视频','4.5万点赞', '678评论', '旅行达人', '2:56', $r("app.media.RecommendItemC"), $r('app.media.userA'),'Video/City_Night_View.mp4'),
  new TrendingItem(5, 'comedy', '办公室日常搞笑小剧场，职场人士共鸣','舞蹈视频', '16.8万点赞', '3.2k评论', '搞笑达人', '1:12', $r("app.media.pixels"), $r('app.media.userC'),'Video/City_Night_View.mp4'),
  new TrendingItem(6, 'fitness', '在家也能练出马甲线，零器械腹肌训练','舞蹈视频', '7.3万点赞', '954评论', '健身教练', '4:38', $r("app.media.RecommendItemC"), $r('app.media.userA'),'Video/City_Night_View.mp4'),
  new TrendingItem(7, 'dance', '现代舞《破晓》，表达内心挣扎与希望','舞蹈视频', '5.6万点赞', '876评论', '现代舞团', '2:15', $r("app.media.pixels"), $r('app.media.userB'),'Video/City_Night_View.mp4'),
  new TrendingItem(8, 'music', '民谣翻唱《江湖夜雨》，感受传统音乐魅力','江湖夜雨', '9.4万点赞', '1.5k评论', '歌手小林', '2:54', $r("app.media.pixels"), $r('app.media.userB'),'Music/shots.mp3'),
  new TrendingItem(9, 'food', '探店系列：城市里最隐秘的米其林餐厅','舞蹈视频', '11.2万点赞', '2.3k评论', '美食博主', '5:28', $r("app.media.RecommendItemB"), $r('app.media.userA'),'Video/City_Night_View.mp4'),
  new TrendingItem(10, 'comedy', '宠物日常，当猫咪遇到狗狗的爆笑瞬间','舞蹈视频', '20.5万点赞', '4.7k评论', '搞笑达人', '0:58', $r("app.media.RecommendItemA"), $r('app.media.userC'),'Video/City_Night_View.mp4'),
  new TrendingItem(11, 'music', '歌曲结合了中国传统音乐元素与现代流行编曲','秋殇别恋', '27.5万点赞', '4.7k评论', '格子兮', '4:57', $r("app.media.QMusic"), $r('app.media.userA'),'Music/秋殇别恋.mp3'),
]
export {TrendingContentList}